# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      # Runs a single command using the runners shell
      - name: Building
        run: |
              echo Building
              cl /EHsc main.cpp
              ls
      - name: artifacting
        uses: actions/upload-artifact@v2
        with: 
            name: sort_exe_artifact
            path: "*.exe"
            retention-days: 2
  telegram:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - uses: actions/download-artifact@master
      - uses: appleboy/telegram-action@master 
        with:
          name: send_to_bot
          to: ${{ secrets.TELEGRAM_TO_DEBUG }} 
          token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }} 
          message: Safronov Ivan
          document: "/home/runner/work/gha_cpp-SidNotSus/gha_cpp-SidNotSus/sort_exe_artifact/*.exe"
